//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E.Deezer.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E.Deezer.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;All&quot;,&quot;picture&quot;:&quot;http://api.deezer.com/genre/0/image&quot;,&quot;picture_small&quot;:&quot;http://cdn-images.deezer.com/images/misc//56x56-000000-80-0-0.jpg&quot;,&quot;picture_medium&quot;:&quot;http://cdn-images.deezer.com/images/misc//250x250-000000-80-0-0.jpg&quot;,&quot;picture_big&quot;:&quot;http://cdn-images.deezer.com/images/misc//500x500-000000-80-0-0.jpg&quot;,&quot;type&quot;:&quot;genre&quot;},{&quot;id&quot;:132,&quot;name&quot;:&quot;Pop&quot;,&quot;picture&quot;:&quot;http://api.deezer.com/genre/132/image&quot;,&quot;picture_small&quot;:&quot;http://cdn-images.deezer.com/images/misc/db7a604d9e7634a67d45cfc86b48370a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenreAll {
            get {
                return ResourceManager.GetString("GenreAll", resourceCulture);
            }
        }
    }
}
